[package]
name = "AT2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
eframe = "0.31.1"
egui = "0.31.1"
env_logger = "0.11.6"
cpal = "0.15.3"
rand = "0.9.0"
rfd = "0.15.2"
crossbeam-channel = "0.5.8"
midir = "0.10.0"
hound = "3.5.1"
egui_plot = "0.31.0"